### ISSUE TITLE
Channel

### ISSUE THREAD

**Issue by gamefundas** [techfort/redisvue#2]
Can this be used to subscribe to channels and view the data in real time? This can prove to be a fantastic real time data stream viewer as we push out logs to Redis channels.

**Comment by techfort** [comment]
@gamefundas well it uses a plain psubscribe with the pattern provided at connection time https://github.com/techfort/redisvue/blob/master/src/renderer/store/index.js#L44 so it should receive anything sent on a channel that matches the pattern. I haven't yet catered for plain pub/sub because i believe the data received has a slightly different structure to event notifications but let me investigate a bit. Other than that I could implement a pub/sub viewer screen, it should be easy enough.

**Comment by gamefundas** [comment]
Oh great. The data in Pubsub is typically a json object. The keys are channel names from the publisher standpoint.  So if someone subscribes to channels based on a pattern then we receive events in the form of json objects which can simply be shown as values. 

The key difference in terms of visualization is that we should maintain a view buffer (x items) and render only the items in buffer in UI for performance reasons. The view keeps scrolling to the bottom will give the nice log tailing effect as new data is published.

**Comment by techfort** [comment]
@gamefundas i have a ifrst prototype of the pub sub working in master. I didn't yet have time to address the buffer so I `unshift` entries to the array of messages received, that way the most recent is at the top. Let me know if this is going in the right direction so i can then put some kind of UI in place to let the user specify the buffer size. I tested this with multiple channels and it works well, since it isn't so rare that you would want to listen to more channels.

**Comment by gamefundas** [comment]
@techfort this is good start. For the most part people will be selecting channels to view so if there is a way to choose from a drop down list or something it will be nice addition. It will also make sense to have some kind of field that allows the user to filter messages based on some pattern. May be some simple expression language that can evaluate and show only matched data. 

As for the view, need to see how this performs when contents are replaced constantly. I will try to get this running on some production load to see how it handles real time log data. I think given that this view can get intense with constant change of state, some kind of virtual DOM appends might be more efficient in the long run.

**Comment by techfort** [comment]
@gamefundas i'll be pulling the list of active channels from redis using `PUBSUB CHANNELS` but i will also leave the ability to subscribe to a channel because if a channel does not have active listeners it won't turn up on `PUBSUB CHANNELS`. As for the view, this project was really combining two goals: 1. creating a redis viewer that would satisfy my needs (eg. inspect how a key value changed through history, real time visualization of traffic, set operations previews etc.) and 2. learn Vue.js. I'm no FE developer but i believe Vue works off the virtual DOM, if not :man_shrugging:

**Comment by gamefundas** [comment]
@techfort thanks for the update. Once the initial version of this feature makes it to the next release I will test and see how I can contribute. Have some JS experience.

Also, would like to know if I can build this as a web application?

**Comment by techfort** [comment]
@gamefundas i am not sure about building this as a web app since it uses a tcp redis client , i can't imagine it working correctly from inside a browser but maybe it can be done. 
As for the pubsub screen, it's kind of done, by default it will show the first 100 messages, although it retains them all, i might add a button to clear the data from memory to avoid crashes and the ability to increase the number of messages to display.

**Comment by techfort** [comment]
hey @gamefundas - i'm happy enough with how this works at the moment so i'm going to close this, let me know if you have further improvements to be made to this.
